project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-On Ex
        menu: 
          - text: Hands-On Ex 1
            href: handson_ex1.html
      - text: In-Class Ex
        menu: 
          - text: In-Class Ex 01
            href: InClassEx/Ex01/inclass_Ex01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

