project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-On Ex
        menu: 
          - text: Hands-On Ex 1
            href: HandsOnEx/HandsOnEx1/handson_ex1.html
          - text: Hands-On Ex 2
            href: HandsOnEx/HandsOnEx2/handsonex2.html
          - text: Hands-On Ex 3
            href: HandsOnEx/HandsOnEx3/Handson_Ex03.html
      - text: In-Class Ex
        menu: 
          - text: In-Class Ex 01
            href: InClassEx/Ex01/inclass_Ex01.html
          - text: In-Class Ex 02
            href: InClassEx/Ex02/inclass_ex02.html
          - text: In-Class Ex 03
            href: InClassEx/Ex02/inclass_Ex03.html
      - text: Take-Home Ex
        menu: 
          - text: Take-Home Ex 01
            href: TakehomeEx/Ex01/takehomeex1.html
          - text: Take-Home Ex 02
            href: TakehomeEx/Ex01/takehomeex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

